Update AMI tags to be configurable during the packer build
openshift/quay-image-builder pull request #13
Opened 2023-02-27 21:24 UTC by dmc5179

Update to allow tags like RHEL and OS_VERSION to be set correctly during the build and not hard coded. Also update default to 4.12.3

2023-02-28 16:01 UTC, bparry02 requested changes
The builders.ami_name and builders.ami_description values should be changed to:

```
OCP-Content-{{user `ocp_ver`}}-{{isotime \"2006-01-02-150405\"}}
```

If the timestamp format can be changed to remove the hyphens it might make it easier to read.

2023-02-28 16:01 UTC, bparry02 commented on aws-rhel8-quay.json
> +    "purpose": "Quay Registry for OpenShift {{env `OCP_MAJ_VER`}}",
We should clarify the description to indicate this is an OCP content AMI and registry, something like:

```suggestion
    "ami_description": "OpenShift {{env `OCP_MAJ_VER`}} content and registry",
    "purpose": "OpenShift {{env `OCP_MAJ_VER`}} content and registry",
```

Although I'm not sure the ami_description variable here is used, so it could be omitted.

2023-03-08 02:52 UTC, dmc5179 reviewed
lgtm

2023-03-08 02:53 UTC, dmc5179 reviewed
lgtm

2023-03-08 02:53 UTC, dmc5179 reviewed
lgtm

2023-03-09 01:29 UTC, bparry02 approved these changes

2023-03-09 09:27 UTC, merged